# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackctl < Formula
  desc "A fast, single-binary Slack CLI for AI agents and humans"
  homepage "https://github.com/cluas/slackctl"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.6/slackctl_darwin_amd64.tar.gz"
      sha256 "0046d2a5ecc529038eecafd2cea079473c0e0eb84376796422f4a9915fc8b10a"

      define_method(:install) do
        bin.install "slackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.6/slackctl_darwin_arm64.tar.gz"
      sha256 "8ab61de0f499370612474651e9c86c6d997219816ac975f600b36130a8ba24f1"

      define_method(:install) do
        bin.install "slackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.6/slackctl_linux_amd64.tar.gz"
      sha256 "cd4239bd3af53e30a95573d4337c29cf642ee186bf8c6f8dfa30e17ff6ede972"
      define_method(:install) do
        bin.install "slackctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.6/slackctl_linux_arm64.tar.gz"
      sha256 "9aa6b5fcae0f5d141ab9dcf2c66612e107990c1cc41a62be307dcfac15333de3"
      define_method(:install) do
        bin.install "slackctl"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slackctl --version")
  end
end
