# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackctl < Formula
  desc "A fast, single-binary Slack CLI for AI agents and humans"
  homepage "https://github.com/cluas/slackctl"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.4/slackctl_darwin_amd64.tar.gz"
      sha256 "fa8f26e8da3c023d9ef17dc27e1ef01f732a70e84640b42d97839c751745bc5c"

      define_method(:install) do
        bin.install "slackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.4/slackctl_darwin_arm64.tar.gz"
      sha256 "fb167184e4abc88acc47e3b98f3811dd2bac67f190c97715b7991d4cce7e01bb"

      define_method(:install) do
        bin.install "slackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.4/slackctl_linux_amd64.tar.gz"
      sha256 "1a782f7da87fab5809bb742e6a5457b80f7bf01bbdf032ead166bd7c69b85312"
      define_method(:install) do
        bin.install "slackctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.4/slackctl_linux_arm64.tar.gz"
      sha256 "83d509a93a4a84a3630b089bd9c48681e326927bd3b1aeb427823bad3bbdcb10"
      define_method(:install) do
        bin.install "slackctl"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slackctl --version")
  end
end
