# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackctl < Formula
  desc "A fast, single-binary Slack CLI for AI agents and humans"
  homepage "https://github.com/cluas/slackctl"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.5/slackctl_darwin_amd64.tar.gz"
      sha256 "07cb711690890082797fd1f56ad903eb87feacbd3ba6b3075cdbb48da4b62742"

      define_method(:install) do
        bin.install "slackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.5/slackctl_darwin_arm64.tar.gz"
      sha256 "4f6a1816b0b9daae2b61b33cdf0c18b5f1bc505ae6397aa35d598d02eb3ceae1"

      define_method(:install) do
        bin.install "slackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.5/slackctl_linux_amd64.tar.gz"
      sha256 "6cbaff597f301452d52905b44f4d8fcdf1f7f47f7374e1c44bafaeeba3e4b421"
      define_method(:install) do
        bin.install "slackctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluas/slackctl/releases/download/v0.1.5/slackctl_linux_arm64.tar.gz"
      sha256 "e916a314fac37162ae7c40477482bb8fe2398c0940c90593ccb85c9a23b1d6d2"
      define_method(:install) do
        bin.install "slackctl"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slackctl --version")
  end
end
